version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: link-api-server
    command: yarn dev
    environment:
      - MORGAN_LOGGER=true
      - MORGAN_BODY_LOGGER=true
      - EXPRESS_DEV_LOGGER=true
      - LOGGER_LEVEL=debug
      - BLING_KEY=b3fa0e8853db33ba978d7cd53e7df0ebef2d2e4fda9cefbed1df108acf0d543450f5237b
      - BLING_URL=
      - PIPEDRIVE_URL=https://teste64.pipedrive.com/api/v1
      - PIPEDRIVE_TOKEN=2e724a0f6210dfef0dabf4be37b8f450d2b3fe36
      - PORT=3333
      - NODE_ENV=dev
      - MONGO_PORT=27017
      - MONGO_HOST=link-api-mongo
      - REDIS_PORT=6379
      - REDIS_HOST=link-api-redis

    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - mongo
    networks:
      - backend-network
  mongo:
    image: 'docker.io/bitnami/mongodb:4.4-debian-10'
    container_name: link-api-mongo
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    networks:
      - backend-network
  redis:
    image: redis:alpine
    container_name: link-api-redis
    ports:
      - "6379:6379"
    volumes:
      - /redisdb/conf:/usr/local/etc/redis
volumes:
  mongodb_data:
    driver: local

networks:
  backend-network:
    driver: bridge
